=== jsamsoninfo76/m1-bda/transpole.dtd
<!ELEMENT transpole (itineraire)* >
  <!ELEMENT itineraire (depart,arrivee, mode,preferences,vitessePieton,trajet) >
    <!ATTLIST itineraire date CDATA #REQUIRED>
    <!ATTLIST itineraire heure CDATA #REQUIRED>
  <!ELEMENT depart (#PCDATA) >
    <!ATTLIST depart ville CDATA #REQUIRED>
  <!ELEMENT arrivee (#PCDATA) >
    <!ATTLIST arrivee ville CDATA #REQUIRED>
  <!ELEMENT mode (metro?,bus?,tramway?,car?) >
  <!ELEMENT preferences (vitesse) >
  <!ELEMENT vitesse (#PCDATA) >
  <!ELEMENT vitessePieton (#PCDATA) >
  <!ELEMENT trajet (pieton | bus | correspondance | metro | tramway | car)* >
    <!ATTLIST trajet duree CDATA #REQUIRED>
    <!ATTLIST trajet unite CDATA #REQUIRED>
  <!ELEMENT metro (#PCDATA) >
    <!ATTLIST metro duree CDATA #IMPLIED>
    <!ATTLIST metro ligne CDATA #IMPLIED>
    <!ATTLIST metro heure CDATA #IMPLIED>
    <!ATTLIST metro direction CDATA #IMPLIED>
    <!ATTLIST metro ville_arrivee CDATA #IMPLIED>
  <!ELEMENT bus (#PCDATA) >
    <!ATTLIST bus duree CDATA #IMPLIED>
    <!ATTLIST bus ligne CDATA #IMPLIED>
    <!ATTLIST bus heure CDATA #IMPLIED>
    <!ATTLIST bus direction CDATA #IMPLIED>
    <!ATTLIST bus ville_arrivee CDATA #IMPLIED>
  <!ELEMENT tramway (#PCDATA) >
    <!ATTLIST tramway duree CDATA #IMPLIED>
    <!ATTLIST tramway ligne CDATA #IMPLIED>
    <!ATTLIST tramway heure CDATA #IMPLIED>
    <!ATTLIST tramway direction CDATA #IMPLIED>
    <!ATTLIST tramway ville_arrivee CDATA #IMPLIED>
  <!ELEMENT car (#PCDATA) >
    <!ATTLIST car duree CDATA #IMPLIED>
    <!ATTLIST car ligne CDATA #IMPLIED>
    <!ATTLIST car heure CDATA #IMPLIED>
    <!ATTLIST car direction CDATA #IMPLIED>
    <!ATTLIST car ville_arrivee CDATA #IMPLIED>
  <!ELEMENT pieton (#PCDATA) >
    <!ATTLIST pieton duree CDATA #REQUIRED>
    <!ATTLIST pieton ville_arrivee CDATA #REQUIRED>
    <!ATTLIST pieton heure CDATA #REQUIRED>
  <!ELEMENT correspondance EMPTY >
    <!ATTLIST correspondance duree CDATA #REQUIRED>
    <!ATTLIST correspondance heure CDATA #REQUIRED>

=== jsamsoninfo76/m1-bda/transpole.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE transpole SYSTEM "transpole.dtd">
<!--<?xml-stylesheet href="stylesheets/transpole.css" type="text/css"?> -->

<!-- New document created with EditiX at Mon Jan 28 20:45:38 CET 2013 -->


<transpole>
	<itineraire date="Mardi 22 janvier 2013" heure="12h35">
		<depart ville="Seclin">Centre Hospitalier</depart>
		<arrivee ville="Roubaix">Avenue Motte</arrivee>
		<mode>
			<metro/>
			<bus/>
			<tramway/>
			<car/>
		</mode>
		<preferences>
			<vitesse>Rapide</vitesse>
		</preferences>
		<vitessePieton>Normale</vitessePieton>
		<trajet duree="87" unite="minutes">
			<pieton duree="13" ville_arrivee="Seclin" heure="">Hôtel de ville</pieton>
			<bus duree="23" ligne="52" heure="14h51" direction="Lille - Porte des postes" ville_arrivee="Lille">Porte des postes</bus>
			<correspondance duree="4" heure="15h14"/>
			<metro duree="3" ligne="1" heure="15h18" direction="Villeneuve d’Ascq - 4 Cantons Grand Stade" ville_arrivee="Lille">Porte des postes</metro>
			<correspondance duree="6" heure="15h21"/>
			<metro duree="25" ligne="2" heure="15h27" direction="Tourcoing - CH Dron" ville_arrivee="Roubaix">Epeule Montesquieu</metro>
			<correspondance duree="4" heure="15h52"/>
			<bus duree="9" ligne="52" heure="15h56" direction="Roubaix - fraternité" ville_arrivee="Roubaix">Porte des postes</bus>
		</trajet>
	</itineraire>
</transpole>
