=== jsamsoninfo76/m1-bda/branches/tp02/fichiers-bda-2/univ.dtd
<!ELEMENT universite (enseignant*,cours*,salle*, etudiant*)*>
  <!ELEMENT enseignant (nom, matiere*, cours_enseign*)>
  <!ELEMENT cours (code, titre, salle_cours)>
  <!ELEMENT salle EMPTY>
    <!ATTLIST salle numero ID #REQUIRED>
  <!ELEMENT etudiant (nom,numero,cours_suivi*)>
  <!ELEMENT nom (#PCDATA) >
  <!ELEMENT matiere (#PCDATA) >
  <!ELEMENT titre (#PCDATA) >
  <!ELEMENT numero (#PCDATA) >
  <!ELEMENT code EMPTY >
    <!ATTLIST code id_cours ID #REQUIRED>
  <!ELEMENT cours_suivi EMPTY >
    <!ATTLIST cours_suivi id_cours IDREF #REQUIRED>
  <!ELEMENT cours_enseign EMPTY >
    <!ATTLIST cours_enseign id_cours IDREF #REQUIRED>
  <!ELEMENT salle_cours EMPTY >
    <!ATTLIST salle_cours numero IDREF #REQUIRED>

=== jsamsoninfo76/m1-bda/fichiers-bda-2/univ.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE universite SYSTEM "univ.dtd">


<universite>
	<enseignant>
		<nom>Toto</nom>
		<matiere>bases de données</matiere>
		<matiere>site web</matiere>
		<cours_enseign id_cours="LI345"/>
		<cours_enseign id_cours="LI349"/>
	</enseignant>
	<enseignant>
		<nom>Titi</nom>
		<matiere>langage</matiere>
		<cours_enseign id_cours="LI349"/>
	</enseignant>
	<cours>
		<code id_cours="LI345"/>
		<titre>bases de données et sites Web</titre>
		<salle_cours numero="Amphi_B1"/>
	</cours>
	<cours>
		<code id_cours="LI349"/>
		<titre>compilation</titre>
		<salle_cours numero="Amphi_B2"/>
	</cours>
	<salle numero="Amphi_B1"/>
	<salle numero="Amphi_B2"/>
	<etudiant>
		<nom>Jermiiiiiie</nom>
		<numero>12</numero>
		<cours_suivi id_cours="LI349"/>
	</etudiant>
		
</universite>
